include: package:flutter_lints/flutter.yaml
  
analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart

linter:
  rules:
    library_prefixes: false
    prefer_function_declarations_over_variables: false