include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    no_wildcard_variable_uses: ignore
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart

linter:
  rules:
    library_prefixes: false
    prefer_function_declarations_over_variables: false
