name: vouchervault
description: A new Flutter project.
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=2.10.0-7.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  barcode_scan: ^3.0.1
  barcode_widget: ^1.5.0
  bloc_stream: ^4.5.0
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  equatable: ^1.2.5
  eyro_toast: ^0.1.0
  file_picker: ^2.1.1
  flutter_bloc_stream: ^4.4.0
  flutter_form_builder: ^3.14.0
  flutter_hooks: ^0.14.1
  functional_widget_annotation: ^0.8.0
  intl: ^0.16.1
  json_annotation: ^3.0.1
  path_provider: ^1.6.24
  persisted_bloc_stream: ^4.3.2
  provider: ^4.3.2
  screen: ^0.0.5
  share: ^0.6.5
  time: ^1.3.0
  timeago: ^2.0.27
  uuid: ^2.2.2

dev_dependencies:
  build_runner: ^1.10.2
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  functional_widget: ^0.8.0
  json_serializable: ^3.4.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # - images/a_dot_ham.jpeg
  fonts:
    - family: Alegreya Sans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Regular.ttf
        - asset: assets/fonts/AlegreyaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AlegreyaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/AlegreyaSans-Black.ttf
          weight: 900
        - asset: assets/fonts/AlegreyaSans-BlackItalic.ttf
          weight: 900
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: assets/icon/icon_bg.png
  adaptive_icon_foreground: assets/icon/icon_fg.png
