name: vouchervault
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.10.0-7.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^3.0.1
  barcode_widget: ^1.5.0
  bloc_stream: ^4.3.1
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  equatable: ^1.2.5
  flutter_bloc_stream: ^4.3.0
  flutter_form_builder: ^3.14.0
  google_fonts: ^1.1.0
  intl: ^0.16.1
  json_annotation: ^3.0.1
  persisted_bloc_stream: ^4.3.2
  provider: ^4.3.2
  time: ^1.3.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  json_serializable: ^3.4.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
