name: vouchervault
description: A new Flutter project.
publish_to: "none"
version: 1.0.10+10

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  barcode_scan: ^3.0.1
  barcode_widget: ^2.0.0
  bloc_stream: ^5.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  eyro_toast: ^0.1.0
  file_picker: ^3.0.0
  flutter_bloc_stream: ^5.0.0
  flutter_form_builder: ^4.2.0
  flutter_hooks: ^0.16.0
  functional_widget_annotation: ^0.8.0
  intl: ^0.17.0
  json_annotation: ^3.1.0
  path_provider: ^2.0.1
  persisted_bloc_stream: ^5.0.2
  provider: ^5.0.0
  screen: ^0.0.5
  share: ^2.0.0
  time: ^1.5.0-nullsafety.1
  timeago: ^3.0.1
  uuid: ^3.0.1
  
dependency_overrides:
  crypto: ^3.0.0-nullsafety.0
  date_range_picker:
    git:
      url: https://github.com/LempereurBenjamin/date_range_picker
  flutter_keyboard_visibility: ^5.0.0
  image: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^1.10.2
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  functional_widget: ^0.8.0
  json_serializable: ^3.4.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # - images/a_dot_ham.jpeg
  fonts:
    - family: Alegreya Sans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Regular.ttf
        - asset: assets/fonts/AlegreyaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AlegreyaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/AlegreyaSans-Black.ttf
          weight: 900
        - asset: assets/fonts/AlegreyaSans-BlackItalic.ttf
          weight: 900
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: assets/icon/icon_bg.png
  adaptive_icon_foreground: assets/icon/icon_fg.png
