name: vouchervault
description: A new Flutter project.
publish_to: "none"
version: 1.1.8+26

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  barcode_widget: ^2.0.0
  persisted_bloc_stream: ^6.0.1
  riverpod_bloc_stream: ^7.0.1
  brightness_volume: ^1.0.3
  cupertino_icons: ^1.0.2
  dart_date: ^1.1.0
  datetime_picker_formfield: ^2.0.0
  enum_utils: ^0.2.0
  file_picker: ^4.0.0
  flutter_form_builder: ^7.0.0
  flutter_hooks: ^0.18.0
  fluttertoast: ^8.0.7
  form_builder_validators: ^7.1.0
  fpdt: ^0.0.35
  freezed_annotation: ^1.0.0
  functional_widget_annotation: ^0.9.2
  intl: ^0.17.0
  local_auth: ^1.1.8
  logging: ^1.0.2
  json_annotation: ^4.4.0
  path_provider: ^2.0.1
  qr_code_scanner: ^0.6.1
  hooks_riverpod: ^1.0.0
  share: ^2.0.0
  uuid: ^3.0.1

dev_dependencies:
  build_runner: ^2.0.1
  emulators: ^0.2.0
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  functional_widget: ^0.9.2
  json_serializable: ^6.0.1
  test: any

flutter:
  uses-material-design: true

  fonts:
    - family: Alegreya Sans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Regular.ttf
        - asset: assets/fonts/AlegreyaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AlegreyaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/AlegreyaSans-Black.ttf
          weight: 900
        - asset: assets/fonts/AlegreyaSans-BlackItalic.ttf
          weight: 900
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: assets/icon/icon_bg.png
  adaptive_icon_foreground: assets/icon/icon_fg.png
