name: vouchervault
description: A new Flutter project.
publish_to: "none"
version: 1.0.17+17

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  barcode_widget: ^2.0.0
  bloc_stream: ^5.0.1
  brightness_volume: ^1.0.3
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  file_picker: ^4.0.0
  flutter_form_builder: ^6.0.1
  flutter_hooks: ^0.18.0
  fluttertoast: ^8.0.7
  fpdart: ^0.0.11
  freezed_annotation: ^0.14.0
  functional_widget_annotation: ^0.9.0
  intl: ^0.17.0
  json_annotation: ^4.1.0
  path_provider: ^2.0.1
  persisted_bloc_stream: ^5.0.2
  qr_code_scanner: ^0.5.1
  hooks_riverpod: ^1.0.0-dev.7
  riverpod_bloc_stream: ^7.0.0-dev.1
  share: ^2.0.0
  time: ^2.0.0
  timeago: ^3.0.1
  uuid: ^3.0.1

dependency_overrides:
  functional_widget:
    git:
      url: https://github.com/tim-smart/functional_widget.git
      ref: chwidget
      path: packages/functional_widget
  functional_widget_annotation:
    git:
      url: https://github.com/tim-smart/functional_widget.git
      ref: chwidget
      path: packages/functional_widget_annotation

dev_dependencies:
  build_runner: ^2.0.1
  emulators: ^0.1.13
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.0
  functional_widget: ^0.9.0
  json_serializable: ^5.0.0
  test: ^1.17.0

flutter:
  uses-material-design: true

  fonts:
    - family: Alegreya Sans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Regular.ttf
        - asset: assets/fonts/AlegreyaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AlegreyaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/AlegreyaSans-Black.ttf
          weight: 900
        - asset: assets/fonts/AlegreyaSans-BlackItalic.ttf
          weight: 900
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: assets/icon/icon_bg.png
  adaptive_icon_foreground: assets/icon/icon_fg.png
