name: vouchervault
description: A new Flutter project.
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  barcode_widget: ^2.0.0
  camera: ^0.10.0
  dart_date: ^1.1.0
  file_picker: ^5.0.0
  flutter_form_builder: ^7.5.0
  flutter_hooks: ^0.18.0
  flutter_nucleus: ^0.1.5
  fluttertoast: ^8.0.7
  form_builder_validators: ^8.1.1
  fpdt: ^0.0.62
  freezed_annotation: ^2.0.3
  functional_widget_annotation: ^0.10.0
  google_mlkit_barcode_scanning: ^0.4.0
  google_mlkit_entity_extraction: ^0.5.0
  google_mlkit_text_recognition: ^0.4.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  local_auth: ^2.1.0
  logging: ^1.0.2
  path_provider: ^2.0.1
  recase: ^4.0.0
  rxdart: ^0.27.5
  share: ^2.0.0
  screen_brightness: ^0.2.1
  uuid: ^3.0.1
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.0.1
  emulators: ^0.4.10
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  functional_widget: ^0.10.0
  json_serializable: ^6.0.1
  test: any

flutter:
  uses-material-design: true

  fonts:
    - family: Alegreya Sans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Regular.ttf
        - asset: assets/fonts/AlegreyaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AlegreyaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/AlegreyaSans-Black.ttf
          weight: 900
        - asset: assets/fonts/AlegreyaSans-BlackItalic.ttf
          weight: 900
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: assets/icon/icon_bg.png
  adaptive_icon_foreground: assets/icon/icon_fg.png
